/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicCartRouteImport } from './routes/_public/cart'
import { Route as AppCheckoutRouteImport } from './routes/_app/checkout'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiImgRefIdRouteImport } from './routes/api/img.$refId'
import { Route as PublicProductsSlugRouteImport } from './routes/_public/products.$slug'
import { Route as AppOrdersOrderNumberRouteImport } from './routes/_app/orders.$orderNumber'
import { Route as AppAdminProductsIndexRouteImport } from './routes/_app/admin/products.index'
import { Route as AppAdminOrdersIndexRouteImport } from './routes/_app/admin/orders.index'
import { Route as AppAdminProductsIdRouteImport } from './routes/_app/admin/products.$id'
import { Route as AppAdminOrdersOrderNumberRouteImport } from './routes/_app/admin/orders.$orderNumber'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiImgRefIdRoute = ApiImgRefIdRouteImport.update({
  id: '/api/img/$refId',
  path: '/api/img/$refId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AppOrdersOrderNumberRoute = AppOrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProductsIndexRoute = AppAdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrdersIndexRoute = AppAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProductsIdRoute = AppAdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrdersOrderNumberRoute =
  AppAdminOrdersOrderNumberRouteImport.update({
    id: '/orders/$orderNumber',
    path: '/orders/$orderNumber',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/checkout': typeof AppCheckoutRoute
  '/cart': typeof PublicCartRoute
  '/orders/$orderNumber': typeof AppOrdersOrderNumberRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/api/img/$refId': typeof ApiImgRefIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/admin/orders/$orderNumber': typeof AppAdminOrdersOrderNumberRoute
  '/admin/products/$id': typeof AppAdminProductsIdRoute
  '/admin/orders/': typeof AppAdminOrdersIndexRoute
  '/admin/products/': typeof AppAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/checkout': typeof AppCheckoutRoute
  '/cart': typeof PublicCartRoute
  '/orders/$orderNumber': typeof AppOrdersOrderNumberRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/api/img/$refId': typeof ApiImgRefIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/admin/orders/$orderNumber': typeof AppAdminOrdersOrderNumberRoute
  '/admin/products/$id': typeof AppAdminProductsIdRoute
  '/admin/orders': typeof AppAdminOrdersIndexRoute
  '/admin/products': typeof AppAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/checkout': typeof AppCheckoutRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/orders/$orderNumber': typeof AppOrdersOrderNumberRoute
  '/_public/products/$slug': typeof PublicProductsSlugRoute
  '/api/img/$refId': typeof ApiImgRefIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/admin/orders/$orderNumber': typeof AppAdminOrdersOrderNumberRoute
  '/_app/admin/products/$id': typeof AppAdminProductsIdRoute
  '/_app/admin/orders/': typeof AppAdminOrdersIndexRoute
  '/_app/admin/products/': typeof AppAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/cart'
    | '/orders/$orderNumber'
    | '/products/$slug'
    | '/api/img/$refId'
    | '/admin/'
    | '/orders/'
    | '/admin/orders/$orderNumber'
    | '/admin/products/$id'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/cart'
    | '/orders/$orderNumber'
    | '/products/$slug'
    | '/api/img/$refId'
    | '/admin'
    | '/orders'
    | '/admin/orders/$orderNumber'
    | '/admin/products/$id'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/admin'
    | '/_app/checkout'
    | '/_public/cart'
    | '/_public/'
    | '/_app/orders/$orderNumber'
    | '/_public/products/$slug'
    | '/api/img/$refId'
    | '/_app/admin/'
    | '/_app/orders/'
    | '/_app/admin/orders/$orderNumber'
    | '/_app/admin/products/$id'
    | '/_app/admin/orders/'
    | '/_app/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiImgRefIdRoute: typeof ApiImgRefIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/img/$refId': {
      id: '/api/img/$refId'
      path: '/api/img/$refId'
      fullPath: '/api/img/$refId'
      preLoaderRoute: typeof ApiImgRefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/orders/$orderNumber': {
      id: '/_app/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof AppOrdersOrderNumberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/products/': {
      id: '/_app/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AppAdminProductsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/orders/': {
      id: '/_app/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AppAdminOrdersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/products/$id': {
      id: '/_app/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AppAdminProductsIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/orders/$orderNumber': {
      id: '/_app/admin/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/admin/orders/$orderNumber'
      preLoaderRoute: typeof AppAdminOrdersOrderNumberRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminOrdersOrderNumberRoute: typeof AppAdminOrdersOrderNumberRoute
  AppAdminProductsIdRoute: typeof AppAdminProductsIdRoute
  AppAdminOrdersIndexRoute: typeof AppAdminOrdersIndexRoute
  AppAdminProductsIndexRoute: typeof AppAdminProductsIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminOrdersOrderNumberRoute: AppAdminOrdersOrderNumberRoute,
  AppAdminProductsIdRoute: AppAdminProductsIdRoute,
  AppAdminOrdersIndexRoute: AppAdminOrdersIndexRoute,
  AppAdminProductsIndexRoute: AppAdminProductsIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppOrdersOrderNumberRoute: typeof AppOrdersOrderNumberRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCheckoutRoute: AppCheckoutRoute,
  AppOrdersOrderNumberRoute: AppOrdersOrderNumberRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicCartRoute: typeof PublicCartRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCartRoute: PublicCartRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProductsSlugRoute: PublicProductsSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiImgRefIdRoute: ApiImgRefIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
