/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as OrdersOrderNumberRouteImport } from './routes/orders.$orderNumber'
import { Route as ObjectsProductIdRouteImport } from './routes/objects.$productId'
import { Route as OperatorMediaStoreProductsProductIdRouteImport } from './routes/[_]operator.media.store.products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderNumberRoute = OrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsProductIdRoute = ObjectsProductIdRouteImport.update({
  id: '/objects/$productId',
  path: '/objects/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorMediaStoreProductsProductIdRoute =
  OperatorMediaStoreProductsProductIdRouteImport.update({
    id: '/_operator/media/store/products/$productId',
    path: '/_operator/media/store/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/objects/$productId': typeof ObjectsProductIdRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/objects/': typeof ObjectsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/_operator/media/store/products/$productId': typeof OperatorMediaStoreProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/objects/$productId': typeof ObjectsProductIdRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/objects': typeof ObjectsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/_operator/media/store/products/$productId': typeof OperatorMediaStoreProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/objects/$productId': typeof ObjectsProductIdRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/objects/': typeof ObjectsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/_operator/media/store/products/$productId': typeof OperatorMediaStoreProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/objects/$productId'
    | '/orders/$orderNumber'
    | '/objects/'
    | '/orders/'
    | '/_operator/media/store/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/objects/$productId'
    | '/orders/$orderNumber'
    | '/objects'
    | '/orders'
    | '/_operator/media/store/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/objects/$productId'
    | '/orders/$orderNumber'
    | '/objects/'
    | '/orders/'
    | '/_operator/media/store/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObjectsProductIdRoute: typeof ObjectsProductIdRoute
  OrdersOrderNumberRoute: typeof OrdersOrderNumberRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OperatorMediaStoreProductsProductIdRoute: typeof OperatorMediaStoreProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderNumber': {
      id: '/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof OrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$productId': {
      id: '/objects/$productId'
      path: '/objects/$productId'
      fullPath: '/objects/$productId'
      preLoaderRoute: typeof ObjectsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/media/store/products/$productId': {
      id: '/_operator/media/store/products/$productId'
      path: '/_operator/media/store/products/$productId'
      fullPath: '/_operator/media/store/products/$productId'
      preLoaderRoute: typeof OperatorMediaStoreProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObjectsProductIdRoute: ObjectsProductIdRoute,
  OrdersOrderNumberRoute: OrdersOrderNumberRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OperatorMediaStoreProductsProductIdRoute:
    OperatorMediaStoreProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
