/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextsIndexRouteImport } from './routes/texts.index'
import { Route as SoftwareIndexRouteImport } from './routes/software.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as TextsTextIdRouteImport } from './routes/texts.$textId'
import { Route as SoftwareSoftwareIdRouteImport } from './routes/software.$softwareId'
import { Route as PagesKeyRouteImport } from './routes/pages.$key'
import { Route as OrdersOrderNumberRouteImport } from './routes/orders.$orderNumber'
import { Route as ObjectsProductIdRouteImport } from './routes/objects.$productId'
import { Route as OperatorMediaStoreProductsProductIdRouteImport } from './routes/[_]operator.media.store.products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextsIndexRoute = TextsIndexRouteImport.update({
  id: '/texts/',
  path: '/texts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareIndexRoute = SoftwareIndexRouteImport.update({
  id: '/software/',
  path: '/software/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextsTextIdRoute = TextsTextIdRouteImport.update({
  id: '/texts/$textId',
  path: '/texts/$textId',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareSoftwareIdRoute = SoftwareSoftwareIdRouteImport.update({
  id: '/software/$softwareId',
  path: '/software/$softwareId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesKeyRoute = PagesKeyRouteImport.update({
  id: '/pages/$key',
  path: '/pages/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderNumberRoute = OrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsProductIdRoute = ObjectsProductIdRouteImport.update({
  id: '/objects/$productId',
  path: '/objects/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorMediaStoreProductsProductIdRoute =
  OperatorMediaStoreProductsProductIdRouteImport.update({
    id: '/_operator/media/store/products/$productId',
    path: '/_operator/media/store/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/objects/$productId': typeof ObjectsProductIdRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/pages/$key': typeof PagesKeyRoute
  '/software/$softwareId': typeof SoftwareSoftwareIdRoute
  '/texts/$textId': typeof TextsTextIdRoute
  '/media/': typeof MediaIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/texts/': typeof TextsIndexRoute
  '/_operator/media/store/products/$productId': typeof OperatorMediaStoreProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/objects/$productId': typeof ObjectsProductIdRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/pages/$key': typeof PagesKeyRoute
  '/software/$softwareId': typeof SoftwareSoftwareIdRoute
  '/texts/$textId': typeof TextsTextIdRoute
  '/media': typeof MediaIndexRoute
  '/objects': typeof ObjectsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/pages': typeof PagesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/software': typeof SoftwareIndexRoute
  '/texts': typeof TextsIndexRoute
  '/_operator/media/store/products/$productId': typeof OperatorMediaStoreProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/objects/$productId': typeof ObjectsProductIdRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/pages/$key': typeof PagesKeyRoute
  '/software/$softwareId': typeof SoftwareSoftwareIdRoute
  '/texts/$textId': typeof TextsTextIdRoute
  '/media/': typeof MediaIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/texts/': typeof TextsIndexRoute
  '/_operator/media/store/products/$productId': typeof OperatorMediaStoreProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/objects/$productId'
    | '/orders/$orderNumber'
    | '/pages/$key'
    | '/software/$softwareId'
    | '/texts/$textId'
    | '/media/'
    | '/objects/'
    | '/orders/'
    | '/pages/'
    | '/settings/'
    | '/software/'
    | '/texts/'
    | '/_operator/media/store/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/objects/$productId'
    | '/orders/$orderNumber'
    | '/pages/$key'
    | '/software/$softwareId'
    | '/texts/$textId'
    | '/media'
    | '/objects'
    | '/orders'
    | '/pages'
    | '/settings'
    | '/software'
    | '/texts'
    | '/_operator/media/store/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/objects/$productId'
    | '/orders/$orderNumber'
    | '/pages/$key'
    | '/software/$softwareId'
    | '/texts/$textId'
    | '/media/'
    | '/objects/'
    | '/orders/'
    | '/pages/'
    | '/settings/'
    | '/software/'
    | '/texts/'
    | '/_operator/media/store/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObjectsProductIdRoute: typeof ObjectsProductIdRoute
  OrdersOrderNumberRoute: typeof OrdersOrderNumberRoute
  PagesKeyRoute: typeof PagesKeyRoute
  SoftwareSoftwareIdRoute: typeof SoftwareSoftwareIdRoute
  TextsTextIdRoute: typeof TextsTextIdRoute
  MediaIndexRoute: typeof MediaIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SoftwareIndexRoute: typeof SoftwareIndexRoute
  TextsIndexRoute: typeof TextsIndexRoute
  OperatorMediaStoreProductsProductIdRoute: typeof OperatorMediaStoreProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texts/': {
      id: '/texts/'
      path: '/texts'
      fullPath: '/texts/'
      preLoaderRoute: typeof TextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/': {
      id: '/software/'
      path: '/software'
      fullPath: '/software/'
      preLoaderRoute: typeof SoftwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texts/$textId': {
      id: '/texts/$textId'
      path: '/texts/$textId'
      fullPath: '/texts/$textId'
      preLoaderRoute: typeof TextsTextIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/$softwareId': {
      id: '/software/$softwareId'
      path: '/software/$softwareId'
      fullPath: '/software/$softwareId'
      preLoaderRoute: typeof SoftwareSoftwareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$key': {
      id: '/pages/$key'
      path: '/pages/$key'
      fullPath: '/pages/$key'
      preLoaderRoute: typeof PagesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderNumber': {
      id: '/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof OrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$productId': {
      id: '/objects/$productId'
      path: '/objects/$productId'
      fullPath: '/objects/$productId'
      preLoaderRoute: typeof ObjectsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/media/store/products/$productId': {
      id: '/_operator/media/store/products/$productId'
      path: '/_operator/media/store/products/$productId'
      fullPath: '/_operator/media/store/products/$productId'
      preLoaderRoute: typeof OperatorMediaStoreProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObjectsProductIdRoute: ObjectsProductIdRoute,
  OrdersOrderNumberRoute: OrdersOrderNumberRoute,
  PagesKeyRoute: PagesKeyRoute,
  SoftwareSoftwareIdRoute: SoftwareSoftwareIdRoute,
  TextsTextIdRoute: TextsTextIdRoute,
  MediaIndexRoute: MediaIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PagesIndexRoute: PagesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SoftwareIndexRoute: SoftwareIndexRoute,
  TextsIndexRoute: TextsIndexRoute,
  OperatorMediaStoreProductsProductIdRoute:
    OperatorMediaStoreProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
