#!/usr/bin/env bun
/**
 * Solo-mode dev (docs/ops/05 §3.4): run ONE worker locally with its
 * service/D1/queue/R2 bindings pointed at the DEPLOYED STAGING fleet, instead
 * of booting six local siblings. Because each wrangler.jsonc's top level IS
 * the staging section, stamping `"remote": true` onto the top-level bindings
 * resolves them to the live staging workers with zero extra mapping.
 *
 * Usage (from a worker dir, via its `dev:solo` script):  bun ../../scripts/dev-solo.ts [wrangler dev args…]
 *
 * This is a DEV OVERLAY, not config generation: the checked-in wrangler.jsonc
 * stays untouched; the stamped copy is written to wrangler.solo.jsonc in the
 * worker root (gitignored — must sit beside wrangler.jsonc so relative paths
 * like `main` resolve) and handed to `wrangler dev -c`. `remote` is a dev-only wrangler
 * key ("Whether the binding should be remote or not in local development" —
 * wrangler config-schema.json); it has no effect on deploys.
 *
 * Requires Cloudflare auth (CLOUDFLARE_API_TOKEN or `wrangler login`) — remote
 * bindings proxy through your account. The all-local fleet (`bun run dev` at
 * root) remains the canonical path for cross-worker work and schema changes.
 *
 * Scope guard: keep this ≤ ~60 lines and dev-only — it must never grow into a
 * second render-wrangler (docs/ops/02 §4 deleted that on purpose).
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { parse as parseJsonc } from "jsonc-parser";

const cwd = process.cwd();
const configPath = resolve(cwd, "wrangler.jsonc");
if (!existsSync(configPath)) {
  console.error("dev-solo: no wrangler.jsonc in cwd — run via a worker's `bun run dev:solo`.");
  process.exit(1);
}

const hasToken = !!process.env.CLOUDFLARE_API_TOKEN;
const hasLogin =
  existsSync(resolve(homedir(), ".wrangler")) ||
  existsSync(resolve(homedir(), "Library/Preferences/.wrangler"));
if (!hasToken && !hasLogin) {
  console.error(
    "dev-solo: remote bindings need Cloudflare auth — set CLOUDFLARE_API_TOKEN or `wrangler login` first.",
  );
  process.exit(1);
}

type Binding = Record<string, unknown>;
interface WranglerConfig {
  services?: Binding[];
  d1_databases?: Binding[];
  r2_buckets?: Binding[];
  queues?: { producers?: Binding[]; consumers?: Binding[] };
  [k: string]: unknown;
}
const cfg = parseJsonc(readFileSync(configPath, "utf8")) as WranglerConfig;

// Top-level (staging) bindings only — env.production is never touched in dev.
for (const b of cfg.services ?? []) b.remote = true;
for (const b of cfg.d1_databases ?? []) b.remote = true;
for (const b of cfg.r2_buckets ?? []) b.remote = true;
for (const b of cfg.queues?.producers ?? []) b.remote = true;
// (consumers can't be remote — the local worker consumes nothing in solo mode.)

// The stamped copy MUST live in the worker root: wrangler resolves relative
// config paths (main, migrations_dir, assets…) against the CONFIG FILE's
// directory, so a copy under .wrangler/ breaks every one of them.
const outPath = resolve(cwd, "wrangler.solo.jsonc");
writeFileSync(
  outPath,
  `// GENERATED by scripts/dev-solo.ts — wrangler.jsonc + "remote": true on dev bindings. Do not edit or commit.\n${JSON.stringify(cfg, null, 2)}\n`,
);

console.log("dev-solo: local worker + REMOTE STAGING bindings (services/D1/R2/queue producers)");
const result = spawnSync("bunx", ["wrangler", "dev", "-c", outPath, ...process.argv.slice(2)], {
  cwd,
  stdio: "inherit",
});
process.exit(result.status ?? 1);
