/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SproutAdminRouteImport } from './routes/sprout-admin'
import { Route as HubRouteImport } from './routes/hub'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as SproutAdminIndexRouteImport } from './routes/sprout-admin/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalIndexRouteImport } from './routes/_portal/index'
import { Route as WsSplatRouteImport } from './routes/ws/$'
import { Route as SproutAdminCredentialsRouteImport } from './routes/sprout-admin/credentials'
import { Route as HubNotificationsRouteImport } from './routes/hub/notifications'
import { Route as BSlugRouteImport } from './routes/b/$slug'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminFulfilmentRouteImport } from './routes/admin/fulfilment'
import { Route as AdminCallsRouteImport } from './routes/admin/calls'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as PortalRequestsRouteImport } from './routes/_portal/requests'
import { Route as PortalHomeRouteImport } from './routes/_portal/home'
import { Route as AdminContentQuizzesRouteImport } from './routes/admin/content/quizzes'
import { Route as AdminContentFeedRouteImport } from './routes/admin/content/feed'
import { Route as AdminContentDropsRouteImport } from './routes/admin/content/drops'
import { Route as AdminContentDecksRouteImport } from './routes/admin/content/decks'
import { Route as AdminContentBannersRouteImport } from './routes/admin/content/banners'
import { Route as AdminContentAssetsRouteImport } from './routes/admin/content/assets'

const SproutAdminRoute = SproutAdminRouteImport.update({
  id: '/sprout-admin',
  path: '/sprout-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SproutAdminIndexRoute = SproutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SproutAdminRoute,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const WsSplatRoute = WsSplatRouteImport.update({
  id: '/ws/$',
  path: '/ws/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SproutAdminCredentialsRoute = SproutAdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => SproutAdminRoute,
} as any)
const HubNotificationsRoute = HubNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HubRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFulfilmentRoute = AdminFulfilmentRouteImport.update({
  id: '/fulfilment',
  path: '/fulfilment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallsRoute = AdminCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const PortalRequestsRoute = PortalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHomeRoute = PortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalRoute,
} as any)
const AdminContentQuizzesRoute = AdminContentQuizzesRouteImport.update({
  id: '/content/quizzes',
  path: '/content/quizzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentFeedRoute = AdminContentFeedRouteImport.update({
  id: '/content/feed',
  path: '/content/feed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentDropsRoute = AdminContentDropsRouteImport.update({
  id: '/content/drops',
  path: '/content/drops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentDecksRoute = AdminContentDecksRouteImport.update({
  id: '/content/decks',
  path: '/content/decks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentBannersRoute = AdminContentBannersRouteImport.update({
  id: '/content/banners',
  path: '/content/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentAssetsRoute = AdminContentAssetsRouteImport.update({
  id: '/content/assets',
  path: '/content/assets',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/sprout-admin': typeof SproutAdminRouteWithChildren
  '/home': typeof PortalHomeRoute
  '/requests': typeof PortalRequestsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/fulfilment': typeof AdminFulfilmentRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/api/$': typeof ApiSplatRoute
  '/b/$slug': typeof BSlugRoute
  '/hub/notifications': typeof HubNotificationsRoute
  '/sprout-admin/credentials': typeof SproutAdminCredentialsRoute
  '/ws/$': typeof WsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/hub/': typeof HubIndexRoute
  '/sprout-admin/': typeof SproutAdminIndexRoute
  '/admin/content/assets': typeof AdminContentAssetsRoute
  '/admin/content/banners': typeof AdminContentBannersRoute
  '/admin/content/decks': typeof AdminContentDecksRoute
  '/admin/content/drops': typeof AdminContentDropsRoute
  '/admin/content/feed': typeof AdminContentFeedRoute
  '/admin/content/quizzes': typeof AdminContentQuizzesRoute
}
export interface FileRoutesByTo {
  '/home': typeof PortalHomeRoute
  '/requests': typeof PortalRequestsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/fulfilment': typeof AdminFulfilmentRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/api/$': typeof ApiSplatRoute
  '/b/$slug': typeof BSlugRoute
  '/hub/notifications': typeof HubNotificationsRoute
  '/sprout-admin/credentials': typeof SproutAdminCredentialsRoute
  '/ws/$': typeof WsSplatRoute
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminIndexRoute
  '/hub': typeof HubIndexRoute
  '/sprout-admin': typeof SproutAdminIndexRoute
  '/admin/content/assets': typeof AdminContentAssetsRoute
  '/admin/content/banners': typeof AdminContentBannersRoute
  '/admin/content/decks': typeof AdminContentDecksRoute
  '/admin/content/drops': typeof AdminContentDropsRoute
  '/admin/content/feed': typeof AdminContentFeedRoute
  '/admin/content/quizzes': typeof AdminContentQuizzesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/sprout-admin': typeof SproutAdminRouteWithChildren
  '/_portal/home': typeof PortalHomeRoute
  '/_portal/requests': typeof PortalRequestsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/calls': typeof AdminCallsRoute
  '/admin/fulfilment': typeof AdminFulfilmentRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/api/$': typeof ApiSplatRoute
  '/b/$slug': typeof BSlugRoute
  '/hub/notifications': typeof HubNotificationsRoute
  '/sprout-admin/credentials': typeof SproutAdminCredentialsRoute
  '/ws/$': typeof WsSplatRoute
  '/_portal/': typeof PortalIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/hub/': typeof HubIndexRoute
  '/sprout-admin/': typeof SproutAdminIndexRoute
  '/admin/content/assets': typeof AdminContentAssetsRoute
  '/admin/content/banners': typeof AdminContentBannersRoute
  '/admin/content/decks': typeof AdminContentDecksRoute
  '/admin/content/drops': typeof AdminContentDropsRoute
  '/admin/content/feed': typeof AdminContentFeedRoute
  '/admin/content/quizzes': typeof AdminContentQuizzesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hub'
    | '/sprout-admin'
    | '/home'
    | '/requests'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/calls'
    | '/admin/fulfilment'
    | '/admin/inbox'
    | '/admin/reviews'
    | '/admin/setup'
    | '/api/$'
    | '/b/$slug'
    | '/hub/notifications'
    | '/sprout-admin/credentials'
    | '/ws/$'
    | '/admin/'
    | '/hub/'
    | '/sprout-admin/'
    | '/admin/content/assets'
    | '/admin/content/banners'
    | '/admin/content/decks'
    | '/admin/content/drops'
    | '/admin/content/feed'
    | '/admin/content/quizzes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/requests'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/calls'
    | '/admin/fulfilment'
    | '/admin/inbox'
    | '/admin/reviews'
    | '/admin/setup'
    | '/api/$'
    | '/b/$slug'
    | '/hub/notifications'
    | '/sprout-admin/credentials'
    | '/ws/$'
    | '/'
    | '/admin'
    | '/hub'
    | '/sprout-admin'
    | '/admin/content/assets'
    | '/admin/content/banners'
    | '/admin/content/decks'
    | '/admin/content/drops'
    | '/admin/content/feed'
    | '/admin/content/quizzes'
  id:
    | '__root__'
    | '/_portal'
    | '/admin'
    | '/hub'
    | '/sprout-admin'
    | '/_portal/home'
    | '/_portal/requests'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/calls'
    | '/admin/fulfilment'
    | '/admin/inbox'
    | '/admin/reviews'
    | '/admin/setup'
    | '/api/$'
    | '/b/$slug'
    | '/hub/notifications'
    | '/sprout-admin/credentials'
    | '/ws/$'
    | '/_portal/'
    | '/admin/'
    | '/hub/'
    | '/sprout-admin/'
    | '/admin/content/assets'
    | '/admin/content/banners'
    | '/admin/content/decks'
    | '/admin/content/drops'
    | '/admin/content/feed'
    | '/admin/content/quizzes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  HubRoute: typeof HubRouteWithChildren
  SproutAdminRoute: typeof SproutAdminRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  BSlugRoute: typeof BSlugRoute
  WsSplatRoute: typeof WsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sprout-admin': {
      id: '/sprout-admin'
      path: '/sprout-admin'
      fullPath: '/sprout-admin'
      preLoaderRoute: typeof SproutAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprout-admin/': {
      id: '/sprout-admin/'
      path: '/'
      fullPath: '/sprout-admin/'
      preLoaderRoute: typeof SproutAdminIndexRouteImport
      parentRoute: typeof SproutAdminRoute
    }
    '/hub/': {
      id: '/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/ws/$': {
      id: '/ws/$'
      path: '/ws/$'
      fullPath: '/ws/$'
      preLoaderRoute: typeof WsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprout-admin/credentials': {
      id: '/sprout-admin/credentials'
      path: '/credentials'
      fullPath: '/sprout-admin/credentials'
      preLoaderRoute: typeof SproutAdminCredentialsRouteImport
      parentRoute: typeof SproutAdminRoute
    }
    '/hub/notifications': {
      id: '/hub/notifications'
      path: '/notifications'
      fullPath: '/hub/notifications'
      preLoaderRoute: typeof HubNotificationsRouteImport
      parentRoute: typeof HubRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fulfilment': {
      id: '/admin/fulfilment'
      path: '/fulfilment'
      fullPath: '/admin/fulfilment'
      preLoaderRoute: typeof AdminFulfilmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calls': {
      id: '/admin/calls'
      path: '/calls'
      fullPath: '/admin/calls'
      preLoaderRoute: typeof AdminCallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/requests': {
      id: '/_portal/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof PortalRequestsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/home': {
      id: '/_portal/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PortalHomeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/content/quizzes': {
      id: '/admin/content/quizzes'
      path: '/content/quizzes'
      fullPath: '/admin/content/quizzes'
      preLoaderRoute: typeof AdminContentQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/feed': {
      id: '/admin/content/feed'
      path: '/content/feed'
      fullPath: '/admin/content/feed'
      preLoaderRoute: typeof AdminContentFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/drops': {
      id: '/admin/content/drops'
      path: '/content/drops'
      fullPath: '/admin/content/drops'
      preLoaderRoute: typeof AdminContentDropsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/decks': {
      id: '/admin/content/decks'
      path: '/content/decks'
      fullPath: '/admin/content/decks'
      preLoaderRoute: typeof AdminContentDecksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/banners': {
      id: '/admin/content/banners'
      path: '/content/banners'
      fullPath: '/admin/content/banners'
      preLoaderRoute: typeof AdminContentBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/assets': {
      id: '/admin/content/assets'
      path: '/content/assets'
      fullPath: '/admin/content/assets'
      preLoaderRoute: typeof AdminContentAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PortalRouteChildren {
  PortalHomeRoute: typeof PortalHomeRoute
  PortalRequestsRoute: typeof PortalRequestsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalHomeRoute: PortalHomeRoute,
  PortalRequestsRoute: PortalRequestsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCallsRoute: typeof AdminCallsRoute
  AdminFulfilmentRoute: typeof AdminFulfilmentRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentAssetsRoute: typeof AdminContentAssetsRoute
  AdminContentBannersRoute: typeof AdminContentBannersRoute
  AdminContentDecksRoute: typeof AdminContentDecksRoute
  AdminContentDropsRoute: typeof AdminContentDropsRoute
  AdminContentFeedRoute: typeof AdminContentFeedRoute
  AdminContentQuizzesRoute: typeof AdminContentQuizzesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCallsRoute: AdminCallsRoute,
  AdminFulfilmentRoute: AdminFulfilmentRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentAssetsRoute: AdminContentAssetsRoute,
  AdminContentBannersRoute: AdminContentBannersRoute,
  AdminContentDecksRoute: AdminContentDecksRoute,
  AdminContentDropsRoute: AdminContentDropsRoute,
  AdminContentFeedRoute: AdminContentFeedRoute,
  AdminContentQuizzesRoute: AdminContentQuizzesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HubRouteChildren {
  HubNotificationsRoute: typeof HubNotificationsRoute
  HubIndexRoute: typeof HubIndexRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubNotificationsRoute: HubNotificationsRoute,
  HubIndexRoute: HubIndexRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

interface SproutAdminRouteChildren {
  SproutAdminCredentialsRoute: typeof SproutAdminCredentialsRoute
  SproutAdminIndexRoute: typeof SproutAdminIndexRoute
}

const SproutAdminRouteChildren: SproutAdminRouteChildren = {
  SproutAdminCredentialsRoute: SproutAdminCredentialsRoute,
  SproutAdminIndexRoute: SproutAdminIndexRoute,
}

const SproutAdminRouteWithChildren = SproutAdminRoute._addFileChildren(
  SproutAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  HubRoute: HubRouteWithChildren,
  SproutAdminRoute: SproutAdminRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  BSlugRoute: BSlugRoute,
  WsSplatRoute: WsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
